name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v3
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
          cache: 'pip'
      - name: copy .env
        run: |
          cp contrib/env-sample .env
      - name: dependencies
        run: |
          pip install -r requirements.txt
      - name: flake8
        uses: py-actions/flake8@v1
        with:
          checkName: 'flake8_py3'